### PR TITLE
Signature recipes

### PR DESCRIPTION
**Pull request by kamBhandari**
Signature latte created and added. 
Please review and approve

### CODE REVIEW

**Comment by prakhar7222** [comment]
Please modify the Menu file by adding the reference to the new signature_latte into the menu.

**Review by prakhar7222 — COMMENTED** [review]
Please modify the Menu file by adding the reference to the new signature_latte into the menu.

**Comment by kamBhandari** [comment]
reference added to signature_latte

**Comment by prakhar7222** [comment]
succesfully merged.

**Pull request merged**
